const taxonomyEn: Record<string, string> = {
  '淡水': 'Freshwater',
  '海水': 'Saltwater',
  '冷水': 'Coolwater',
  '广温': 'Wide Temperature Range',
  '热带': 'Tropical',
  '小型': 'Small',
  '中型': 'Medium',
  '大型': 'Large',
  '温和': 'Peaceful',
  '凶猛': 'Aggressive',
  '领地意识强': 'Territorial',
  '极易': 'Easy',
  '中等': 'Medium',
  '困难': 'Hard',
  '灯科鱼': 'Tetras',
  '白云金丝': 'White Cloud Minnows',
  '斑马鱼': 'Danios',
  '鲃类/小型鲤科': 'Barbs / Small Cyprinids',
  '孔雀/月光/玛丽/剑尾': 'Livebearers',
  '鳉鱼': 'Killifish / Ricefish',
  '斗鱼': 'Bettas',
  '曼龙/马甲': 'Gouramis',
  '神仙鱼': 'Angelfish',
  '七彩神仙': 'Discus',
  '短鲷': 'Dwarf Cichlids',
  '慈鲷': 'Cichlids',
  '鼠鱼': 'Corydoras',
  '异型鱼': 'Plecos / Loricariids',
  '清道夫/青苔鼠': 'Algae Eaters',
  '鳅类/吸鳅': 'Loaches / Hillstream Loaches',
  '金鱼': 'Goldfish',
  '锦鲤': 'Koi',
  '雷龙鱼': 'Snakeheads',
  '龙鱼/古代鱼': 'Arowanas / Ancient Fish',
  '美人鱼': 'Rainbowfish',
  '淡水特色鱼': 'Specialty Freshwater Fish',
  '特色观赏鱼': 'Specialty Ornamental Fish',
  '小丑鱼': 'Clownfish',
  '倒吊鱼': 'Tangs',
  '雀鲷': 'Damselfish',
  '海水神仙/蝶鱼': 'Marine Angelfish / Butterflyfish',
  '虾虎/青蛙鱼': 'Gobies / Dragonets',
  '狮子鱼/炮弹鱼': 'Lionfish / Triggerfish',
  '海水特色鱼': 'Specialty Marine Fish',
  '除藻生物': 'Algae Grazers',
  '清残饵生物': 'Detritus Clean-up Crew',
  '翻砂生物': 'Sand Sifters',
  '控螺生物': 'Snail-control Species',
  '观赏虾': 'Ornamental Shrimp',
  '观赏螺': 'Ornamental Snails',
  '观赏蟹': 'Ornamental Crabs',
  '海水清洁生物': 'Marine Clean-up Crew',
  '六角恐龙/蝾螈': 'Axolotls / Newts',
  '蛙类': 'Frogs',
  '龟类': 'Turtles',
  '海葵': 'Anemones',
  '软体珊瑚': 'Soft Corals',
  'LPS硬骨珊瑚': 'LPS Corals',
  'SPS硬骨珊瑚': 'SPS Corals',
  '纽扣/菇类珊瑚': 'Zoanthids / Mushroom Corals',
  '水母': 'Jellyfish',
  '海水滤食生物': 'Marine Filter Feeders',
  '前景草': 'Foreground Plants',
  '莫斯/苔藓': 'Mosses',
  '阴性附生草': 'Low-light Epiphytes',
  '椒草': 'Cryptocoryne',
  '有茎草': 'Stem Plants',
  '中后景莲座草': 'Midground / Background Rosette Plants',
  '浮草': 'Floating Plants',
  '其他水草': 'Other Aquatic Plants',
};

export const localizeTaxonomyLabel = (value: string | null | undefined, isEn: boolean) => {
  if (!value) return '';
  return isEn ? (taxonomyEn[value] || value) : value;
};
