import type { EvidenceSourceDto } from '../../../packages/contracts/src';

const knowledgeSources: Record<string, EvidenceSourceDto> = {
  'seriouslyfish-apistogramma-agassizii': {
    id: 'seriouslyfish-apistogramma-agassizii',
    title: "Apistogramma agassizii (Agassizi's Dwarf Cichlid)",
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/apistogramma-agassizii/',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-apistogramma-agassizii': {
    id: 'fishbase-apistogramma-agassizii',
    title: "Apistogramma agassizii (Agassiz's dwarf cichlid) species summary",
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/Fieldguide/FieldGuideSummary.php?c_code=076&genusname=Apistogramma&speciesname=agassizii',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-trichopodus-leerii': {
    id: 'seriouslyfish-trichopodus-leerii',
    title: 'Trichopodus leerii (Pearl Gourami)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/trichopodus-leerii',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-trichopodus-leerii': {
    id: 'fishbase-trichopodus-leerii',
    title: 'Trichopodus leerii (Pearl gourami) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Trichopodus-leerii.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-phenacogrammus-interruptus': {
    id: 'seriouslyfish-phenacogrammus-interruptus',
    title: 'Phenacogrammus interruptus (Congo Tetra)',
    publisher: 'Seriously Fish',
    url: 'https://seriouslyfish.com/species/phenacogrammus-interruptus',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-phenacogrammus-interruptus': {
    id: 'fishbase-phenacogrammus-interruptus',
    title: 'Phenacogrammus interruptus (Congo tetra) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Phenacogrammus-interruptus.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-sahyadria-denisonii': {
    id: 'seriouslyfish-sahyadria-denisonii',
    title: 'Sahyadria denisonii (Red-line Torpedo Barb)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/sahyadria-denisonii',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-sahyadria-denisonii': {
    id: 'fishbase-sahyadria-denisonii',
    title: 'Dawkinsia denisonii (Denison barb) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Sahyadria-denisonii.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-hyphessobrycon-amandae': {
    id: 'seriouslyfish-hyphessobrycon-amandae',
    title: 'Hyphessobrycon amandae (Ember Tetra)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/hyphessobrycon-amandae',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-hyphessobrycon-amandae': {
    id: 'fishbase-hyphessobrycon-amandae',
    title: 'Hyphessobrycon amandae (Ember tetra) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Hyphessobrycon-amandae.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'aquariumhq-neocaridina-davidi': {
    id: 'aquariumhq-neocaridina-davidi',
    title: 'Cherry shrimp (Neocaridina davidi) care and compatibility',
    publisher: 'AquariumHQ',
    url: 'https://aquariumhq.app/invertebrates/cherry-shrimp',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'zootaxa-neocaridina-sexual-dimorphism': {
    id: 'zootaxa-neocaridina-sexual-dimorphism',
    title: 'Sexual dimorphism in a freshwater atyid shrimp with direct development',
    publisher: 'Zootaxa',
    url: 'https://pubmed.ncbi.nlm.nih.gov/27988685/',
    sourceType: 'peer_reviewed',
    reviewStatus: 'reviewed',
  },
  'aquaculture-research-neocaridina-life-cycle': {
    id: 'aquaculture-research-neocaridina-life-cycle',
    title: 'Breeding and life cycle of the ornamental freshwater shrimp Neocaridina davidi in a biofilm-based culture system',
    publisher: 'Aquaculture Research',
    url: 'https://doi.org/10.1111/are.14733',
    sourceType: 'peer_reviewed',
    reviewStatus: 'reviewed',
  },
  'aquendium-caridina-cantonensis': {
    id: 'aquendium-caridina-cantonensis',
    title: 'Crystal Red Shrimp (Caridina cantonensis) care guide',
    publisher: 'Aquendium',
    url: 'https://aquendium.com/species/crystal-red-shrimp/',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'aquariumhq-neritina-natalensis': {
    id: 'aquariumhq-neritina-natalensis',
    title: 'Nerite snail (Neritina natalensis) care and compatibility',
    publisher: 'AquariumHQ',
    url: 'https://aquariumhq.app/invertebrates/nerite-snail',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-gymnocorymbus-ternetzi': {
    id: 'seriouslyfish-gymnocorymbus-ternetzi',
    title: 'Gymnocorymbus ternetzi (Black Widow Tetra)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/gymnocorymbus-ternetzi',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-gymnocorymbus-ternetzi': {
    id: 'fishbase-gymnocorymbus-ternetzi',
    title: 'Gymnocorymbus ternetzi (Black tetra) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-puntius-titteya': {
    id: 'seriouslyfish-puntius-titteya',
    title: 'Puntius titteya (Cherry Barb)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/puntius-titteya',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-puntius-titteya': {
    id: 'fishbase-puntius-titteya',
    title: 'Puntius titteya (Cherry barb) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Puntius_titteya.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-trigonostigma-heteromorpha': {
    id: 'seriouslyfish-trigonostigma-heteromorpha',
    title: 'Trigonostigma heteromorpha (Harlequin)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/trigonostigma-heteromorpha',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-trigonostigma-heteromorpha': {
    id: 'fishbase-trigonostigma-heteromorpha',
    title: 'Trigonostigma heteromorpha (Harlequin rasbora) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Trigonostigma_heteromorpha.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-xiphophorus-maculatus': {
    id: 'seriouslyfish-xiphophorus-maculatus',
    title: 'Xiphophorus maculatus (Platy)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/xiphophorus-maculatus',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-xiphophorus-maculatus': {
    id: 'fishbase-xiphophorus-maculatus',
    title: 'Xiphophorus maculatus (Southern platyfish) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Xiphophorus_maculatus.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-poecilia-sphenops': {
    id: 'seriouslyfish-poecilia-sphenops',
    title: 'Poecilia sphenops (Short-finned Molly/Black Molly)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/poecilia-sphenops',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-xiphophorus-hellerii': {
    id: 'seriouslyfish-xiphophorus-hellerii',
    title: 'Xiphophorus hellerii (Green Swordtail)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/xiphophorus-hellerii',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-xiphophorus-hellerii': {
    id: 'fishbase-xiphophorus-hellerii',
    title: 'Xiphophorus hellerii (Green swordtail) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.org/Summary/Xiphophorus-hellerii',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-poecilia-reticulata': {
    id: 'seriouslyfish-poecilia-reticulata',
    title: 'Poecilia reticulata (Guppy)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/poecilia-reticulata/',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-poecilia-reticulata': {
    id: 'fishbase-poecilia-reticulata',
    title: 'Poecilia reticulata (Guppy) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Poecilia-reticulata.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-paracheirodon-innesi': {
    id: 'seriouslyfish-paracheirodon-innesi',
    title: 'Paracheirodon innesi (Neon Tetra)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/paracheirodon-innesi',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-paracheirodon-axelrodi': {
    id: 'seriouslyfish-paracheirodon-axelrodi',
    title: 'Paracheirodon axelrodi (Cardinal Tetra)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/paracheirodon-axelrodi',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-tanichthys-albonubes': {
    id: 'seriouslyfish-tanichthys-albonubes',
    title: 'Tanichthys albonubes (White Cloud Mountain Minnow)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/tanichthys-albonubes',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-danio-rerio': {
    id: 'seriouslyfish-danio-rerio',
    title: "Brachydanio rerio (Zebra 'Danio')",
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/danio-rerio',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-corydoras-aeneus': {
    id: 'seriouslyfish-corydoras-aeneus',
    title: 'Corydoras aeneus (Bronze Cory)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/corydoras-aeneus',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-corydoras-panda': {
    id: 'seriouslyfish-corydoras-panda',
    title: 'Corydoras panda (Panda Cory)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/corydoras-panda',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-puntigrus-tetrazona': {
    id: 'seriouslyfish-puntigrus-tetrazona',
    title: 'Puntigrus tetrazona (Tiger Barb)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/puntigrus-tetrazona',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'convict-cichlid-territory-study': {
    id: 'convict-cichlid-territory-study',
    title: 'Sex Differences in How Territory Quality Affects Aggression in Convict Cichlids',
    publisher: 'Integrative and Comparative Biology',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8522484/',
    sourceType: 'peer_reviewed',
    reviewStatus: 'reviewed',
  },
  'small-snakehead-fws-assessment': {
    id: 'small-snakehead-fws-assessment',
    title: 'Ecological Risk Screening Summary: Small Snakehead (Channa asiatica)',
    publisher: 'U.S. Fish and Wildlife Service',
    url: 'https://www.fws.gov/sites/default/files/documents/Ecological-Risk-Screening-Summary-Small-Snakehead.pdf',
    sourceType: 'government',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-betta-splendens': {
    id: 'seriouslyfish-betta-splendens',
    title: 'Betta splendens (Siamese Fighting Fish)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/betta-splendens',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-pterophyllum-scalare': {
    id: 'seriouslyfish-pterophyllum-scalare',
    title: 'Pterophyllum scalare (Angelfish)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/pterophyllum-scalare',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'tamu-pterophyllum-scalare-reproduction': {
    id: 'tamu-pterophyllum-scalare-reproduction',
    title: 'Reproduction of Angelfish (Pterophyllum scalare)',
    publisher: 'Texas A&M AgriLife Extension',
    url: 'https://extension.rwfm.tamu.edu/wp-content/uploads/sites/8/2013/09/Reproduction-of-Angelfish-Pterphyllum-scalare.pdf',
    sourceType: 'government',
    reviewStatus: 'reviewed',
  },
};
export const getKnowledgeSource = (sourceId: string) => knowledgeSources[sourceId];

export const resolveKnowledgeSources = (sourceIds: string[]) => sourceIds
  .map(sourceId => knowledgeSources[sourceId])
  .filter((source): source is EvidenceSourceDto => Boolean(source));
