import type { EvidenceSourceDto } from '../../../packages/contracts/src';

const knowledgeSources: Record<string, EvidenceSourceDto> = {
  'batch29-fishbase-poecilia-sphenops-green': { id: 'batch29-fishbase-poecilia-sphenops-green', title: 'Poecilia sphenops Green variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/4680', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch29-fishbase-poecilia-latipinna-blood': { id: 'batch29-fishbase-poecilia-latipinna-blood', title: 'Poecilia latipinna Blood variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/3226', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch29-fishbase-crossocheilus-langei-gold': { id: 'batch29-fishbase-crossocheilus-langei-gold', title: 'Crossocheilus langei Gold variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Crossocheilus-langei.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch29-fishbase-sahyadria-denisonii-longfin': { id: 'batch29-fishbase-sahyadria-denisonii-longfin', title: 'Sahyadria denisonii Longfin variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Sahyadria-denisonii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch29-fishbase-ancistrus-sp-gold-longfin': { id: 'batch29-fishbase-ancistrus-sp-gold-longfin', title: 'Ancistrus sp. Gold Longfin variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch29-fishbase-poecilia-latipinna-high-fin-red': { id: 'batch29-fishbase-poecilia-latipinna-high-fin-red', title: 'Poecilia latipinna High Fin Red variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/3226', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch29-fishbase-sahyadria-denisonii-red-line': { id: 'batch29-fishbase-sahyadria-denisonii-red-line', title: 'Sahyadria denisonii Red Line variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Sahyadria-denisonii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch29-fishbase-crossocheilus-langei-platinum': { id: 'batch29-fishbase-crossocheilus-langei-platinum', title: 'Crossocheilus langei Platinum variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Crossocheilus-langei.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch29-fishbase-ancistrus-sp-gold-longfin-2': { id: 'batch29-fishbase-ancistrus-sp-gold-longfin-2', title: 'Ancistrus sp. Gold Longfin catalog variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch29-fishbase-ancistrus-sp-white-longfin': { id: 'batch29-fishbase-ancistrus-sp-white-longfin', title: 'Ancistrus sp. White Longfin variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch28-fishbase-ancistrus-sp-longfin-platinum': { id: 'batch28-fishbase-ancistrus-sp-longfin-platinum', title: 'Ancistrus sp. Longfin Platinum variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch28-fishbase-poecilia-sphenops-chocolate': { id: 'batch28-fishbase-poecilia-sphenops-chocolate', title: 'Poecilia sphenops Chocolate variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/4680', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch28-fishbase-carassius-auratus-red-grass': { id: 'batch28-fishbase-carassius-auratus-red-grass', title: 'Carassius auratus Red Grass variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Carassius-auratus.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch28-fishbase-poecilia-latipinna-gold': { id: 'batch28-fishbase-poecilia-latipinna-gold', title: 'Poecilia latipinna Gold variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/3226', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch28-fishbase-poecilia-latipinna-silver': { id: 'batch28-fishbase-poecilia-latipinna-silver', title: 'Poecilia latipinna Silver variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/3226', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch28-fishbase-carassius-auratus-telescope': { id: 'batch28-fishbase-carassius-auratus-telescope', title: 'Carassius auratus Telescope variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Carassius-auratus.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch28-fishbase-lysmata-amboinensis': { id: 'batch28-fishbase-lysmata-amboinensis', title: 'Lysmata amboinensis species review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch28-fishbase-thor-amboinensis': { id: 'batch28-fishbase-thor-amboinensis', title: 'Thor amboinensis species review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch28-fishbase-lysmata-boggesi': { id: 'batch28-fishbase-lysmata-boggesi', title: 'Lysmata boggesi species review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch28-fishbase-sahyadria-denisonii-gold': { id: 'batch28-fishbase-sahyadria-denisonii-gold', title: 'Sahyadria denisonii Gold variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Sahyadria-denisonii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch27-fishbase-carassius-auratus-pearlscale': { id: 'batch27-fishbase-carassius-auratus-pearlscale', title: 'Carassius auratus Pearlscale variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Carassius-auratus.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch27-fishbase-carassius-auratus-bubble-eye': { id: 'batch27-fishbase-carassius-auratus-bubble-eye', title: 'Carassius auratus Bubble Eye variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Carassius-auratus.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch27-aquaplant-cabomba-caroliniana': { id: 'batch27-aquaplant-cabomba-caroliniana', title: 'Cabomba caroliniana species review', publisher: 'Texas A&M AquaPlant', url: 'https://aquaplant.tamu.edu/plant-identification/alphabetical-index/fanwort/carolina-fanwort/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch27-kew-limnophila-aquatica': { id: 'batch27-kew-limnophila-aquatica', title: 'Limnophila aquatica species review', publisher: 'Royal Botanic Gardens, Kew', url: 'https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:331721-2/general-information', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch27-fishbase-sawbwa-resplendens': { id: 'batch27-fishbase-sawbwa-resplendens', title: 'Sawbwa resplendens species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Sawbwa-resplendens', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch27-fishbase-ancistrus-sp': { id: 'batch27-fishbase-ancistrus-sp', title: 'Ancistrus sp. catalog review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch27-fishbase-poecilia-sphenops-balloon': { id: 'batch27-fishbase-poecilia-sphenops-balloon', title: 'Poecilia sphenops Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/4680', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch27-fishbase-carassius-auratus-panda': { id: 'batch27-fishbase-carassius-auratus-panda', title: 'Carassius auratus Panda variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Carassius-auratus.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch27-fishbase-carassius-auratus-oranda-short-tail': { id: 'batch27-fishbase-carassius-auratus-oranda-short-tail', title: 'Carassius auratus Oranda Short Tail variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Carassius-auratus.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch27-fishbase-ancistrus-sp-gold': { id: 'batch27-fishbase-ancistrus-sp-gold', title: 'Ancistrus sp. Gold variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch26-fishbase-trichopodus-trichopterus-blue': { id: 'batch26-fishbase-trichopodus-trichopterus-blue', title: 'Trichopodus trichopterus Blue variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Trichopodus-trichopterus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch26-fishbase-pterois-volitans': { id: 'batch26-fishbase-pterois-volitans', title: 'Pterois volitans species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pterois-volitans.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch26-fishbase-neocaridina-davidi-wild-type': { id: 'batch26-fishbase-neocaridina-davidi-wild-type', title: 'Neocaridina davidi wild type review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch26-fishbase-acheilognathus-macropterus': { id: 'batch26-fishbase-acheilognathus-macropterus', title: 'Acheilognathus macropterus species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Acheilognathus-macropterus.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch26-fishbase-abbottina-rivularis': { id: 'batch26-fishbase-abbottina-rivularis', title: 'Abbottina rivularis species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Abbottina-rivularis', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch26-fishbase-aphyocypris-chinensis': { id: 'batch26-fishbase-aphyocypris-chinensis', title: 'Aphyocypris chinensis species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Aphyocypris_chinensis.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch26-fishbase-carassius-auratus-ranchu': { id: 'batch26-fishbase-carassius-auratus-ranchu', title: 'Carassius auratus Ranchu variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch26-fishbase-carassius-auratus-oranda': { id: 'batch26-fishbase-carassius-auratus-oranda', title: 'Carassius auratus Oranda variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch26-fishbase-carassius-auratus-butterfly-tail': { id: 'batch26-fishbase-carassius-auratus-butterfly-tail', title: 'Carassius auratus Butterfly Tail variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch26-fishbase-carassius-auratus-red-cap': { id: 'batch26-fishbase-carassius-auratus-red-cap', title: 'Carassius auratus Red Cap variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch25-worms-stichodactyla-gigantea-green': { id: 'batch25-worms-stichodactyla-gigantea-green', title: 'Stichodactyla gigantea Green variant review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/aphia.php?id=291133&p=taxdetails', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch25-fishbase-scleropages-formosus-blood-red-a': { id: 'batch25-fishbase-scleropages-formosus-blood-red-a', title: 'Scleropages formosus Blood Red A variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/Summary/Scleropages-formosus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch25-fishbase-scleropages-formosus-gold-head': { id: 'batch25-fishbase-scleropages-formosus-gold-head', title: 'Scleropages formosus Gold Head variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/Summary/Scleropages-formosus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch25-fishbase-potamotrygon-leopoldi-albino': { id: 'batch25-fishbase-potamotrygon-leopoldi-albino', title: 'Potamotrygon leopoldi Albino variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Potamotrygon-leopoldi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch25-fishbase-potamotrygon-leopoldi-eclipse': { id: 'batch25-fishbase-potamotrygon-leopoldi-eclipse', title: 'Potamotrygon leopoldi Eclipse variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Potamotrygon-leopoldi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch25-fishbase-channa-stewartii-karbi-anglong': { id: 'batch25-fishbase-channa-stewartii-karbi-anglong', title: 'Channa stewartii Karbi Anglong variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Channa_stewartii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch25-fishbase-channa-andrao-red': { id: 'batch25-fishbase-channa-andrao-red', title: 'Channa andrao Red variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Channa_andrao.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch25-fishbase-trichopodus-trichopterus-balloon-gold-xl': { id: 'batch25-fishbase-trichopodus-trichopterus-balloon-gold-xl', title: 'Trichopodus trichopterus Balloon Gold XL variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Trichopodus-trichopterus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch25-fishbase-gyrinocheilus-aymonieri': { id: 'batch25-fishbase-gyrinocheilus-aymonieri', title: 'Gyrinocheilus aymonieri species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gyrinocheilus_aymonieri.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch25-fishbase-gyrinocheilus-aymonieri-var': { id: 'batch25-fishbase-gyrinocheilus-aymonieri-var', title: 'Gyrinocheilus aymonieri catalog variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gyrinocheilus_aymonieri.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch24-worms-stichodactyla-haddoni-blue': { id: 'batch24-worms-stichodactyla-haddoni-blue', title: 'Stichodactyla haddoni Blue variant review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch24-worms-stichodactyla-gigantea': { id: 'batch24-worms-stichodactyla-gigantea', title: 'Stichodactyla gigantea species review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/aphia.php?id=291133&p=taxdetails', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch24-fishbase-lutjanus-kasmira-longfin': { id: 'batch24-fishbase-lutjanus-kasmira-longfin', title: 'Lutjanus kasmira Longfin variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/156', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch24-worms-catalaphyllia-jardinei-green': { id: 'batch24-worms-catalaphyllia-jardinei-green', title: 'Catalaphyllia jardinei Green variant review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/aphia.php?p=image&pic=156582&tid=207618', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch24-worms-entacmaea-quadricolor-red': { id: 'batch24-worms-entacmaea-quadricolor-red', title: 'Entacmaea quadricolor Red variant review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch24-worms-chrysaora-quinquecirrha': { id: 'batch24-worms-chrysaora-quinquecirrha', title: 'Chrysaora quinquecirrha species review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch24-worms-chrysaora-melanaster': { id: 'batch24-worms-chrysaora-melanaster', title: 'Chrysaora melanaster species review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch24-worms-sanderia-malayensis': { id: 'batch24-worms-sanderia-malayensis', title: 'Sanderia malayensis species review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/aphia.php?id=220478&p=taxdetails', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch24-worms-catalaphyllia-jardinei-ultra-green': { id: 'batch24-worms-catalaphyllia-jardinei-ultra-green', title: 'Catalaphyllia jardinei Ultra Green variant review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/aphia.php?p=image&pic=156582&tid=207618', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch24-worms-entacmaea-quadricolor-rose': { id: 'batch24-worms-entacmaea-quadricolor-rose', title: 'Entacmaea quadricolor Rose variant review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch23-fishbase-channa-aurantimaculata-gold': { id: 'batch23-fishbase-channa-aurantimaculata-gold', title: 'Channa aurantimaculata Gold variant review', publisher: 'FishBase', url: 'https://fishbase.se/summary/Channa_aurantimaculata.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch23-fishbase-channa-andrao-super-blue': { id: 'batch23-fishbase-channa-andrao-super-blue', title: 'Channa andrao Super Blue variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Channa_andrao.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch23-fishbase-lutjanus-kasmira-var': { id: 'batch23-fishbase-lutjanus-kasmira-var', title: 'Lutjanus kasmira catalog variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/156', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch23-fishbase-pseudochromis-sp-gold': { id: 'batch23-fishbase-pseudochromis-sp-gold', title: 'Pseudochromis sp. Gold catalog variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch23-worms-plerogyra-sinuosa': { id: 'batch23-worms-plerogyra-sinuosa', title: 'Plerogyra sinuosa species review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch23-worms-euphyllia-glabrescens': { id: 'batch23-worms-euphyllia-glabrescens', title: 'Euphyllia glabrescens species review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch23-worms-pachyclavularia-violacea': { id: 'batch23-worms-pachyclavularia-violacea', title: 'Pachyclavularia violacea species review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch23-worms-euphyllia-divisa': { id: 'batch23-worms-euphyllia-divisa', title: 'Euphyllia divisa species review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch23-worms-catalaphyllia-jardinei': { id: 'batch23-worms-catalaphyllia-jardinei', title: 'Catalaphyllia jardinei species review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch23-worms-heteractis-crispa': { id: 'batch23-worms-heteractis-crispa', title: 'Heteractis crispa species review', publisher: 'WoRMS', url: 'https://www.marinespecies.org/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch22-fishbase-dario-dario': { id: 'batch22-fishbase-dario-dario', title: 'Dario dario species review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch22-fishbase-channa-aurantimaculata-gold': { id: 'batch22-fishbase-channa-aurantimaculata-gold', title: 'Channa aurantimaculata Gold variant review', publisher: 'FishBase', url: 'https://fishbase.se/summary/Channa_aurantimaculata.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch22-fishbase-gyrinocheilus-aymonieri-albino': { id: 'batch22-fishbase-gyrinocheilus-aymonieri-albino', title: 'Gyrinocheilus aymonieri Albino variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gyrinocheilus_aymonieri.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch22-fishbase-dario-dario-gold': { id: 'batch22-fishbase-dario-dario-gold', title: 'Dario dario Gold variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch22-fishbase-scleropages-formosus-albino': { id: 'batch22-fishbase-scleropages-formosus-albino', title: 'Scleropages formosus Albino variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/Summary/Scleropages-formosus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch22-fishbase-osphronemus-goramy-gold': { id: 'batch22-fishbase-osphronemus-goramy-gold', title: 'Osphronemus goramy Gold variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/osphronemus-goramy.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch22-fishbase-trichopodus-trichopterus-blue-balloon': { id: 'batch22-fishbase-trichopodus-trichopterus-blue-balloon', title: 'Trichopodus trichopterus Blue Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Trichopodus-trichopterus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch22-fishbase-trichopodus-trichopterus-gold-balloon': { id: 'batch22-fishbase-trichopodus-trichopterus-gold-balloon', title: 'Trichopodus trichopterus Gold Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Trichopodus-trichopterus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch22-fishbase-scleropages-formosus-super-red': { id: 'batch22-fishbase-scleropages-formosus-super-red', title: 'Scleropages formosus Super Red variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/Summary/Scleropages-formosus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch22-fishbase-scleropages-formosus-silver-platinum': { id: 'batch22-fishbase-scleropages-formosus-silver-platinum', title: 'Scleropages formosus Silver Platinum variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/Summary/Scleropages-formosus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch21-fishbase-gymnocorymbus-ternetzi-color-morph': { id: 'batch21-fishbase-gymnocorymbus-ternetzi-color-morph', title: 'Gymnocorymbus ternetzi Color morph variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch21-fishbase-trichopodus-trichopterus-platinum': { id: 'batch21-fishbase-trichopodus-trichopterus-platinum', title: 'Trichopodus trichopterus Platinum variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Trichopodus-trichopterus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch21-fishbase-trichopodus-trichopterus-balloon': { id: 'batch21-fishbase-trichopodus-trichopterus-balloon', title: 'Trichopodus trichopterus Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Trichopodus-trichopterus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch21-fishbase-gnathonemus-petersii': { id: 'batch21-fishbase-gnathonemus-petersii', title: 'Gnathonemus petersii species review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch21-fishbase-xanthichthys-mento': { id: 'batch21-fishbase-xanthichthys-mento', title: 'Xanthichthys mento species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Xanthichthys-mento.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch21-fishbase-centropyge-heraldi': { id: 'batch21-fishbase-centropyge-heraldi', title: 'Centropyge heraldi species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Centropyge-heraldi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch21-fishbase-pomacanthus-annularis': { id: 'batch21-fishbase-pomacanthus-annularis', title: 'Pomacanthus annularis species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pomacanthus_annularis.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch21-fishbase-channa-stewartii': { id: 'batch21-fishbase-channa-stewartii', title: 'Channa stewartii species review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch21-fishbase-channa-diplogramma': { id: 'batch21-fishbase-channa-diplogramma', title: 'Channa diplogramma species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Channa-diplogramma.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch21-fishbase-badis-badis': { id: 'batch21-fishbase-badis-badis', title: 'Badis badis species review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch20-fishbase-osteoglossum-bicirrhosum': { id: 'batch20-fishbase-osteoglossum-bicirrhosum', title: 'Osteoglossum bicirrhosum species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Osteoglossum-bicirrhosum', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch20-fishbase-osteoglossum-ferreirai': { id: 'batch20-fishbase-osteoglossum-ferreirai', title: 'Osteoglossum ferreirai species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Osteoglossum_ferreirai.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch20-fishbase-pantodon-buchholzi': { id: 'batch20-fishbase-pantodon-buchholzi', title: 'Pantodon buchholzi species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pantodon-buchholzi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch20-fishbase-gymnotus-carapo': { id: 'batch20-fishbase-gymnotus-carapo', title: 'Gymnotus carapo species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gymnotus-carapo.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch20-fishbase-botia-almorhae': { id: 'batch20-fishbase-botia-almorhae', title: 'Botia almorhae species review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch20-fishbase-opsariichthys-bidens': { id: 'batch20-fishbase-opsariichthys-bidens', title: 'Opsariichthys bidens species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/27264', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch20-fishbase-mastacembelus-armatus': { id: 'batch20-fishbase-mastacembelus-armatus', title: 'Mastacembelus armatus species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Mastacembelus-armatus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch20-fishbase-leporinus-fasciatus': { id: 'batch20-fishbase-leporinus-fasciatus', title: 'Leporinus fasciatus species review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch20-fishbase-piaractus-brachypomus': { id: 'batch20-fishbase-piaractus-brachypomus', title: 'Piaractus brachypomus species review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch20-fishbase-serrasalmus-rhombeus': { id: 'batch20-fishbase-serrasalmus-rhombeus', title: 'Serrasalmus rhombeus species review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch19-fishbase-mastacembelus-armatus': { id: 'batch19-fishbase-mastacembelus-armatus', title: 'Mastacembelus armatus species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Mastacembelus-armatus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch19-fishbase-channa-barca': { id: 'batch19-fishbase-channa-barca', title: 'Channa barca species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Channa-barca.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch19-fishbase-macropodus-opercularis': { id: 'batch19-fishbase-macropodus-opercularis', title: 'Macropodus opercularis species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Macropodus-opercularis', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch19-fishbase-scleropages-formosus': { id: 'batch19-fishbase-scleropages-formosus', title: 'Scleropages formosus species review', publisher: 'FishBase', url: 'https://www.fishbase.se/Summary/Scleropages-formosus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch19-fishbase-scleropages-formosus-red': { id: 'batch19-fishbase-scleropages-formosus-red', title: 'Scleropages formosus Red variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/6357', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch19-fishbase-polypterus-ornatipinnis': { id: 'batch19-fishbase-polypterus-ornatipinnis', title: 'Polypterus ornatipinnis species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Polypterus-ornatipinnis.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch19-fishbase-channa-bleheri': { id: 'batch19-fishbase-channa-bleheri', title: 'Channa bleheri species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Channa-bleheri.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch19-fishbase-channa-aurantimaculata': { id: 'batch19-fishbase-channa-aurantimaculata', title: 'Channa aurantimaculata species review', publisher: 'FishBase', url: 'https://fishbase.se/summary/Channa_aurantimaculata.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch19-fishbase-channa-lorti': { id: 'batch19-fishbase-channa-lorti', title: 'Channa lorti species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Channa-lorti.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch19-fishbase-scleropages-formosus-green': { id: 'batch19-fishbase-scleropages-formosus-green', title: 'Scleropages formosus Green variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/Summary/Scleropages-formosus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch18-fishbase-neocaridina-davidi-red': { id: 'batch18-fishbase-neocaridina-davidi-red', title: 'Neocaridina davidi Red variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Neocaridina-davidi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch18-fishbase-ambystoma-mexicanum': { id: 'batch18-fishbase-ambystoma-mexicanum', title: 'Ambystoma mexicanum species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Ambystoma-mexicanum.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch18-fishbase-cynops-orientalis': { id: 'batch18-fishbase-cynops-orientalis', title: 'Cynops orientalis species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Cynops-orientalis.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch18-fishbase-ceratophrys-ornata': { id: 'batch18-fishbase-ceratophrys-ornata', title: 'Ceratophrys ornata species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Ceratophrys-ornata.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch18-fishbase-helostoma-temminkii': { id: 'batch18-fishbase-helostoma-temminkii', title: 'Helostoma temminkii species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Helostoma-temminkii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch18-fishbase-lutjanus-kasmira': { id: 'batch18-fishbase-lutjanus-kasmira', title: 'Lutjanus kasmira species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Lutjanus_kasmira.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch18-fishbase-opsariichthys-bidens': { id: 'batch18-fishbase-opsariichthys-bidens', title: 'Opsariichthys bidens species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/27264', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch18-fishbase-macropodus-ocellatus': { id: 'batch18-fishbase-macropodus-ocellatus', title: 'Macropodus ocellatus species review', publisher: 'FishBase', url: 'https://www.fishbase.se/identification/SpeciesList.php?genus=Macropodus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch18-fishbase-macropodus-spechti': { id: 'batch18-fishbase-macropodus-spechti', title: 'Macropodus spechti species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Macropodus-spechti', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch18-fishbase-tachysurus-fulvidraco': { id: 'batch18-fishbase-tachysurus-fulvidraco', title: 'Tachysurus fulvidraco species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pelteobagrus-fulvidraco', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch17-fishbase-andinoacara-pulcher-super-balloon': { id: 'batch17-fishbase-andinoacara-pulcher-super-balloon', title: 'Andinoacara pulcher Super Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Andinoacara_pulcher.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch17-fishbase-mikrogeophagus-ramirezi-super-red-balloon': { id: 'batch17-fishbase-mikrogeophagus-ramirezi-super-red-balloon', title: 'Mikrogeophagus ramirezi Super Red Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/mikrogeophagus-ramirezi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch17-fishbase-danio-rerio-glo-orange-longfin': { id: 'batch17-fishbase-danio-rerio-glo-orange-longfin', title: 'Danio rerio Glo Orange Longfin variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/danio-rerio.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch17-fishbase-gymnocorymbus-ternetzi-platinum-balloon-longfin': { id: 'batch17-fishbase-gymnocorymbus-ternetzi-platinum-balloon-longfin', title: 'Gymnocorymbus ternetzi Platinum Balloon Longfin variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch17-fishbase-neritina-natalensis': { id: 'batch17-fishbase-neritina-natalensis', title: 'Neritina natalensis species review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch17-fishbase-pomacea-bridgesii': { id: 'batch17-fishbase-pomacea-bridgesii', title: 'Pomacea bridgesii species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pomacea-bridgesii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch17-fishbase-labidochromis-caeruleus': { id: 'batch17-fishbase-labidochromis-caeruleus', title: 'Labidochromis caeruleus species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Labidochromis-caeruleus.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch17-fishbase-andinoacara-pulcher': { id: 'batch17-fishbase-andinoacara-pulcher', title: 'Andinoacara pulcher species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Andinoacara_pulcher.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch17-fishbase-amphiprion-ocellaris': { id: 'batch17-fishbase-amphiprion-ocellaris', title: 'Amphiprion ocellaris species review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/amphiprion-ocellaris.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch17-fishbase-pomacea-bridgesii-duplicate-catalog': { id: 'batch17-fishbase-pomacea-bridgesii-duplicate-catalog', title: 'Pomacea bridgesii catalog object review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pomacea-bridgesii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch16-fishbase-andinoacara-pulcher-balloon': { id: 'batch16-fishbase-andinoacara-pulcher-balloon', title: 'Andinoacara pulcher Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Andinoacara-pulcher', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch16-fishbase-hemichromis-bimaculatus-balloon': { id: 'batch16-fishbase-hemichromis-bimaculatus-balloon', title: 'Hemichromis bimaculatus Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hemichromis-bimaculatus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch16-fishbase-astronotus-ocellatus-balloon': { id: 'batch16-fishbase-astronotus-ocellatus-balloon', title: 'Astronotus ocellatus Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Astronotus-ocellatus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch16-fishbase-peckoltia-compta-super-gold': { id: 'batch16-fishbase-peckoltia-compta-super-gold', title: 'Peckoltia compta Super Gold variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/peckoltia-compta.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch16-fishbase-pterophyllum-scalare-super-red': { id: 'batch16-fishbase-pterophyllum-scalare-super-red', title: 'Pterophyllum scalare Super Red variant review', publisher: 'FishBase', url: 'https://www.fishbase.org/summary/Pterophyllum-scalare', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch16-fishbase-gymnocorymbus-ternetzi-platinum-longfin': { id: 'batch16-fishbase-gymnocorymbus-ternetzi-platinum-longfin', title: 'Gymnocorymbus ternetzi Platinum Longfin variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch16-fishbase-gymnocorymbus-ternetzi-glo-orange': { id: 'batch16-fishbase-gymnocorymbus-ternetzi-glo-orange', title: 'Gymnocorymbus ternetzi Glo Orange variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch16-fishbase-chrysiptera-cyanea-platinum': { id: 'batch16-fishbase-chrysiptera-cyanea-platinum', title: 'Chrysiptera cyanea Platinum variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/chrysiptera-cyanea', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch16-fishbase-geophagus-sp-longfin-platinum': { id: 'batch16-fishbase-geophagus-sp-longfin-platinum', title: 'Geophagus sp. Longfin Platinum catalog variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch16-fishbase-xiphophorus-hellerii-high-fin': { id: 'batch16-fishbase-xiphophorus-hellerii-high-fin', title: 'Xiphophorus hellerii High Fin variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Xiphophorus-hellerii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch15-fishbase-danio-rerio-glo-red': { id: 'batch15-fishbase-danio-rerio-glo-red', title: 'Danio rerio Glo Red variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/danio-rerio.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch15-fishbase-danio-rerio-glo-green': { id: 'batch15-fishbase-danio-rerio-glo-green', title: 'Danio rerio Glo Green variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/danio-rerio.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch15-fishbase-danio-rerio-glo-orange': { id: 'batch15-fishbase-danio-rerio-glo-orange', title: 'Danio rerio Glo Orange variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/danio-rerio.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch15-fishbase-gymnocorymbus-ternetzi-albino-balloon': { id: 'batch15-fishbase-gymnocorymbus-ternetzi-albino-balloon', title: 'Gymnocorymbus ternetzi Albino Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch15-fishbase-pelvicachromis-pulcher-albino': { id: 'batch15-fishbase-pelvicachromis-pulcher-albino', title: 'Pelvicachromis pulcher Albino variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pelvicachromis-pulcher.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch15-usgs-aphyocharax-anisitsi-balloon': { id: 'batch15-usgs-aphyocharax-anisitsi-balloon', title: 'Aphyocharax anisitsi Balloon variant review', publisher: 'U.S. Geological Survey', url: 'https://nas.er.usgs.gov/queries/FactSheet.aspx?SpeciesID=416', sourceType: 'government', reviewStatus: 'reviewed' },
  'batch15-fishbase-gymnocorymbus-ternetzi-longfin-white': { id: 'batch15-fishbase-gymnocorymbus-ternetzi-longfin-white', title: 'Gymnocorymbus ternetzi Longfin White variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch15-fishbase-boehlkea-fredcochui-blue': { id: 'batch15-fishbase-boehlkea-fredcochui-blue', title: 'Boehlkea fredcochui Blue variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch15-fishbase-danio-rerio-glo-purple': { id: 'batch15-fishbase-danio-rerio-glo-purple', title: 'Danio rerio Glo Purple variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/danio-rerio.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch15-fishbase-danio-rerio-glo-pink': { id: 'batch15-fishbase-danio-rerio-glo-pink', title: 'Danio rerio Glo Pink variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/danio-rerio.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch14-fishbase-maylandia-estherae-albino': { id: 'batch14-fishbase-maylandia-estherae-albino', title: 'Maylandia estherae Albino variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/60044', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch14-fishbase-sciaenochromis-fryeri-white': { id: 'batch14-fishbase-sciaenochromis-fryeri-white', title: 'Sciaenochromis fryeri White variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Sciaenochromis-fryeri.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch14-fishbase-nimbochromis-livingstonii-var': { id: 'batch14-fishbase-nimbochromis-livingstonii-var', title: 'Nimbochromis livingstonii catalog variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Nimbochromis-livingstonii', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch14-fishbase-altolamprologus-calvus-gold': { id: 'batch14-fishbase-altolamprologus-calvus-gold', title: 'Altolamprologus calvus Gold variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Altolamprologus-calvus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch14-fishbase-geophagus-surinamensis-albino': { id: 'batch14-fishbase-geophagus-surinamensis-albino', title: 'Geophagus surinamensis Albino variant review', publisher: 'FishBase', url: 'https://www.fishbase.org/identification/SpeciesList.php?genus=Geophagus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch14-fishbase-hemichromis-bimaculatus-albino': { id: 'batch14-fishbase-hemichromis-bimaculatus-albino', title: 'Hemichromis bimaculatus Albino variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hemichromis-bimaculatus', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch14-fishbase-pterophyllum-scalare-black-longfin': { id: 'batch14-fishbase-pterophyllum-scalare-black-longfin', title: 'Pterophyllum scalare Black Longfin variant review', publisher: 'FishBase', url: 'https://www.fishbase.org/summary/Pterophyllum-scalare', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch14-fishbase-apistogramma-cacatuoides-super-red': { id: 'batch14-fishbase-apistogramma-cacatuoides-super-red', title: 'Apistogramma cacatuoides Super Red variant review', publisher: 'FishBase', url: 'https://www.fishbase.org/identification/SpeciesList.php?genus=Apistogramma', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch14-fishbase-parancistrus-aurantiacus-gold': { id: 'batch14-fishbase-parancistrus-aurantiacus-gold', title: 'Parancistrus aurantiacus Gold variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Parancistrus_aurantiacus.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch14-fishbase-gymnocorymbus-ternetzi-platinum-longfin': { id: 'batch14-fishbase-gymnocorymbus-ternetzi-platinum-longfin', title: 'Gymnocorymbus ternetzi Platinum Longfin variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch13-fishbase-xiphophorus-hellerii-albino-red': { id: 'batch13-fishbase-xiphophorus-hellerii-albino-red', title: 'Xiphophorus hellerii Albino Red variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Xiphophorus-hellerii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch13-fishbase-pterophyllum-scalare-platinum-longfin': { id: 'batch13-fishbase-pterophyllum-scalare-platinum-longfin', title: 'Pterophyllum scalare Platinum Longfin variant review', publisher: 'FishBase', url: 'https://www.fishbase.org/summary/4717', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch13-fishbase-pterophyllum-scalare-marble-balloon': { id: 'batch13-fishbase-pterophyllum-scalare-marble-balloon', title: 'Pterophyllum scalare Marble Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.org/summary/4717', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch13-fishbase-cichlasoma-blood-parrot-balloon': { id: 'batch13-fishbase-cichlasoma-blood-parrot-balloon', title: 'Cichlasoma Blood Parrot Balloon catalog variant review', publisher: 'FishBase', url: 'https://fishbase.se/identification/SpeciesList.php?genus=Cichlasoma', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch13-fishbase-pterophyllum-scalare-blue-balloon': { id: 'batch13-fishbase-pterophyllum-scalare-blue-balloon', title: 'Pterophyllum scalare Blue Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.org/summary/4717', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch13-fishbase-pomacea-bridgesii-gold': { id: 'batch13-fishbase-pomacea-bridgesii-gold', title: 'Pomacea bridgesii Gold variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pomacea-bridgesii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch13-fishbase-pomacea-bridgesii-blue': { id: 'batch13-fishbase-pomacea-bridgesii-blue', title: 'Pomacea bridgesii Blue variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pomacea-bridgesii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch13-fishbase-pomacea-bridgesii-purple': { id: 'batch13-fishbase-pomacea-bridgesii-purple', title: 'Pomacea bridgesii Purple variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pomacea-bridgesii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch13-fishbase-gymnocorymbus-ternetzi-albino-red-eye': { id: 'batch13-fishbase-gymnocorymbus-ternetzi-albino-red-eye', title: 'Gymnocorymbus ternetzi Albino Red Eye variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch13-fishbase-peckoltia-compta-gold': { id: 'batch13-fishbase-peckoltia-compta-gold', title: 'Peckoltia compta Gold variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/peckoltia-compta.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch12-fishbase-thorichthys-meeki-var': { id: 'batch12-fishbase-thorichthys-meeki-var', title: 'Thorichthys meeki catalog variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Thorichthys-meeki.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch12-fishbase-pelvicachromis-pulcher-albino': { id: 'batch12-fishbase-pelvicachromis-pulcher-albino', title: 'Pelvicachromis pulcher Albino variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pelvicachromis-pulcher.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch12-fishbase-geophagus-sp-platinum': { id: 'batch12-fishbase-geophagus-sp-platinum', title: 'Geophagus sp. Platinum catalog variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch12-fishbase-hyphessobrycon-erythrostigma': { id: 'batch12-fishbase-hyphessobrycon-erythrostigma', title: 'Hyphessobrycon erythrostigma species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hyphessobrycon-erythrostigma.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch12-fishbase-mikrogeophagus-ramirezi-gold-balloon': { id: 'batch12-fishbase-mikrogeophagus-ramirezi-gold-balloon', title: 'Mikrogeophagus ramirezi Gold Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/mikrogeophagus-ramirezi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch12-fishbase-mikrogeophagus-ramirezi-platinum-balloon': { id: 'batch12-fishbase-mikrogeophagus-ramirezi-platinum-balloon', title: 'Mikrogeophagus ramirezi Platinum Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/mikrogeophagus-ramirezi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch12-fishbase-apistogramma-agassizii-fire-red': { id: 'batch12-fishbase-apistogramma-agassizii-fire-red', title: 'Apistogramma agassizii Fire Red variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Apistogramma-agassizii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch12-fishbase-gymnocorymbus-ternetzi-longfin': { id: 'batch12-fishbase-gymnocorymbus-ternetzi-longfin', title: 'Gymnocorymbus ternetzi Longfin variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch12-fishbase-gymnocorymbus-ternetzi-balloon': { id: 'batch12-fishbase-gymnocorymbus-ternetzi-balloon', title: 'Gymnocorymbus ternetzi Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch12-fishbase-nematobrycon-palmeri-platinum': { id: 'batch12-fishbase-nematobrycon-palmeri-platinum', title: 'Nematobrycon palmeri Platinum variant review', publisher: 'FishBase', url: 'https://www.fishbase.org/summary/Nematobrycon-palmeri', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch11-fishbase-pterophyllum-scalare-red': { id: 'batch11-fishbase-pterophyllum-scalare-red', title: 'Pterophyllum scalare Red variant review', publisher: 'FishBase', url: 'https://www.fishbase.org/summary/4717', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch11-fishbase-pterophyllum-scalare-marble': { id: 'batch11-fishbase-pterophyllum-scalare-marble', title: 'Pterophyllum scalare Marble variant review', publisher: 'FishBase', url: 'https://www.fishbase.org/summary/4717', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch11-fishbase-pterophyllum-scalare-blue': { id: 'batch11-fishbase-pterophyllum-scalare-blue', title: 'Pterophyllum scalare Blue variant review', publisher: 'FishBase', url: 'https://www.fishbase.org/summary/4717', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch11-fishbase-pterophyllum-scalare-panda': { id: 'batch11-fishbase-pterophyllum-scalare-panda', title: 'Pterophyllum scalare Panda variant review', publisher: 'FishBase', url: 'https://www.fishbase.org/summary/4717', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch11-fishbase-panaque-sp-l191': { id: 'batch11-fishbase-panaque-sp-l191', title: 'Panaque sp. L191 catalog taxon review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Panaque-nigrolineatus.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch11-fishbase-chrysiptera-cyanea': { id: 'batch11-fishbase-chrysiptera-cyanea', title: 'Chrysiptera cyanea species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/chrysiptera-cyanea', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch11-fishbase-leporacanthicus-cf-galaxias': { id: 'batch11-fishbase-leporacanthicus-cf-galaxias', title: 'Leporacanthicus cf. galaxias catalog taxon review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch11-fishbase-scobinancistrus-aureatus': { id: 'batch11-fishbase-scobinancistrus-aureatus', title: 'Scobinancistrus aureatus species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch11-fishbase-gymnocorymbus-ternetzi-white': { id: 'batch11-fishbase-gymnocorymbus-ternetzi-white', title: 'Gymnocorymbus ternetzi White variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch11-fishbase-aphyocharax-anisitsi-balloon': { id: 'batch11-fishbase-aphyocharax-anisitsi-balloon', title: 'Aphyocharax anisitsi Balloon variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Aphyocharax-anisitsi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch10-fishbase-pterygoplichthys-gibbiceps': { id: 'batch10-fishbase-pterygoplichthys-gibbiceps', title: 'Pterygoplichthys gibbiceps species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pterygoplichthys-gibbiceps.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch10-fishbase-hypancistrus-inspector': { id: 'batch10-fishbase-hypancistrus-inspector', title: 'Hypancistrus inspector species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hypancistrus-inspector.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch10-fishbase-zacco-platypus': { id: 'batch10-fishbase-zacco-platypus', title: 'Zacco platypus species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Zacco_platypus.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch10-fishbase-mikrogeophagus-ramirezi-platinum': { id: 'batch10-fishbase-mikrogeophagus-ramirezi-platinum', title: 'Mikrogeophagus ramirezi Platinum variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/mikrogeophagus-ramirezi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch10-fishbase-danio-rerio-glofish': { id: 'batch10-fishbase-danio-rerio-glofish', title: 'Danio rerio GloFish variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/danio-rerio.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch10-fishbase-mikrogeophagus-ramirezi-blue': { id: 'batch10-fishbase-mikrogeophagus-ramirezi-blue', title: 'Mikrogeophagus ramirezi Blue variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/mikrogeophagus-ramirezi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch10-fishbase-xiphophorus-hellerii-var': { id: 'batch10-fishbase-xiphophorus-hellerii-var', title: 'Xiphophorus hellerii catalog variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Xiphophorus-hellerii.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch10-fishbase-cyprinus-carpio-kohaku': { id: 'batch10-fishbase-cyprinus-carpio-kohaku', title: 'Cyprinus carpio Kohaku variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Cyprinus-carpio.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch10-fishbase-salminus-brasiliensis-var': { id: 'batch10-fishbase-salminus-brasiliensis-var', title: 'Salminus brasiliensis catalog variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/salminus-brasiliensis.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch10-fishbase-gymnocorymbus-ternetzi-albino': { id: 'batch10-fishbase-gymnocorymbus-ternetzi-albino', title: 'Gymnocorymbus ternetzi Albino variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch09-fishbase-hemichromis-bimaculatus': { id: 'batch09-fishbase-hemichromis-bimaculatus', title: 'Hemichromis bimaculatus species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hemichromis-bimaculatus', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch09-fishbase-cichlasoma-var': { id: 'batch09-fishbase-cichlasoma-var', title: 'Cichlasoma var. catalog taxon review', publisher: 'FishBase', url: 'https://www.fishbase.se/search.php?genus=Cichlasoma', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch09-fishbase-heros-severus': { id: 'batch09-fishbase-heros-severus', title: 'Heros severus species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/3617', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch09-fishbase-altolamprologus-calvus': { id: 'batch09-fishbase-altolamprologus-calvus', title: 'Altolamprologus calvus species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Altolamprologus-calvus', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch09-fishbase-neolamprologus-multifasciatus': { id: 'batch09-fishbase-neolamprologus-multifasciatus', title: 'Neolamprologus multifasciatus species summary', publisher: 'FishBase', url: 'https://fishbase.se/summary/8744', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch09-fishbase-moenkhausia-sanctaefilomenae': { id: 'batch09-fishbase-moenkhausia-sanctaefilomenae', title: 'Moenkhausia sanctaefilomenae species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/moenkhausia-sanctaefilomenae.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch09-fishbase-cyprinus-carpio-var': { id: 'batch09-fishbase-cyprinus-carpio-var', title: 'Cyprinus carpio var. catalog taxon review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Cyprinus-carpio.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch09-fishbase-cyprinus-carpio-longfin': { id: 'batch09-fishbase-cyprinus-carpio-longfin', title: 'Cyprinus carpio var. Longfin catalog variant review', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Cyprinus-carpio.html', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch09-fishbase-peckoltia-compta': { id: 'batch09-fishbase-peckoltia-compta', title: 'Peckoltia compta species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Peckoltia-compta', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch09-fishbase-panaque-nigrolineatus': { id: 'batch09-fishbase-panaque-nigrolineatus', title: 'Panaque nigrolineatus species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/12216', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch08-fishbase-clithon-corona': { id: 'batch08-fishbase-clithon-corona', title: 'Clithon corona taxon source', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Clithon-corona.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch08-fishbase-corydoras-aeneus': { id: 'batch08-fishbase-corydoras-aeneus', title: 'Corydoras aeneus species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Corydoras-aeneus.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch08-fishbase-channa-asiatica': { id: 'batch08-fishbase-channa-asiatica', title: 'Channa asiatica species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Channa-asiatica.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch08-fishbase-acrossocheilus-fasciatus': { id: 'batch08-fishbase-acrossocheilus-fasciatus', title: 'Acrossocheilus fasciatus species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Acrossocheilus-fasciatus.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch08-fishbase-chindongo-socolofi': { id: 'batch08-fishbase-chindongo-socolofi', title: 'Chindongo socolofi species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Chindongo-socolofi.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch08-fishbase-pterophyllum-altum': { id: 'batch08-fishbase-pterophyllum-altum', title: 'Pterophyllum altum species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pterophyllum-altum.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch08-fishbase-zebrasoma-flavescens': { id: 'batch08-fishbase-zebrasoma-flavescens', title: 'Zebrasoma flavescens species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Zebrasoma-flavescens.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch08-fishbase-paracanthurus-hepatus': { id: 'batch08-fishbase-paracanthurus-hepatus', title: 'Paracanthurus hepatus species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Paracanthurus-hepatus.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch08-fishbase-hypostomus-plecostomus': { id: 'batch08-fishbase-hypostomus-plecostomus', title: 'Hypostomus plecostomus species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hypostomus-plecostomus.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch08-worms-tylomelania': { id: 'batch08-worms-tylomelania', title: 'Tylomelania WoRMS taxonomic source', publisher: 'WoRMS', url: 'https://www.marinespecies.org/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch08-fishbase-pseudorasbora-parva': { id: 'batch08-fishbase-pseudorasbora-parva', title: 'Pseudorasbora parva species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Pseudorasbora-parva.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch08-fishbase-tylomelania': { id: 'batch08-fishbase-tylomelania', title: 'Tylomelania taxonomic source', publisher: 'WoRMS', url: 'https://www.marinespecies.org/', sourceType: 'professional_association', reviewStatus: 'reviewed' },
  'batch05-fishbase-gastrodermus-hastatus': { id: 'batch05-fishbase-gastrodermus-hastatus', title: 'Gastrodermus hastatus species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Corydoras-hastatus', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch05-fishbase-poropanchax-normani': { id: 'batch05-fishbase-poropanchax-normani', title: 'Poropanchax normani species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Poropanchax-normani.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch05-fishbase-hyphessobrycon-amapaensis': { id: 'batch05-fishbase-hyphessobrycon-amapaensis', title: 'Hyphessobrycon amapaensis species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hyphessobrycon-amapaensis', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch05-fishbase-hyphessobrycon-pulchripinnis': { id: 'batch05-fishbase-hyphessobrycon-pulchripinnis', title: 'Hyphessobrycon pulchripinnis species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hyphessobrycon-pulchripinnis.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch05-fishbase-poecilia-reticulata': { id: 'batch05-fishbase-poecilia-reticulata', title: 'Poecilia reticulata species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Poecilia-reticulata.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch05-fishbase-hemigrammus-bleheri': { id: 'batch05-fishbase-hemigrammus-bleheri', title: 'Hemigrammus bleheri species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hemigrammus-bleheri.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch05-fishbase-paracheirodon-innesi': { id: 'batch05-fishbase-paracheirodon-innesi', title: 'Paracheirodon innesi species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Paracheirodon-innesi.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch06-fishbase-poecilia-reticulata': { id: 'batch06-fishbase-poecilia-reticulata', title: 'Poecilia reticulata species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Poecilia-reticulata.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch06-fishbase-hemigrammus-bleheri': { id: 'batch06-fishbase-hemigrammus-bleheri', title: 'Hemigrammus bleheri species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hemigrammus-bleheri.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch06-fishbase-hyphessobrycon-herbertaxelrodi': { id: 'batch06-fishbase-hyphessobrycon-herbertaxelrodi', title: 'Hyphessobrycon herbertaxelrodi species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hyphessobrycon-herbertaxelrodi.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch06-fishbase-paracheirodon-innesi': { id: 'batch06-fishbase-paracheirodon-innesi', title: 'Paracheirodon innesi species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Paracheirodon-innesi.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch06-fishbase-hemigrammus-rodwayi': { id: 'batch06-fishbase-hemigrammus-rodwayi', title: 'Hemigrammus rodwayi species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hemigrammus-rodwayi.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch06-fishbase-corydoras-panda': { id: 'batch06-fishbase-corydoras-panda', title: 'Corydoras panda species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Corydoras-panda.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch06-fishbase-corydoras-aeneus': { id: 'batch06-fishbase-corydoras-aeneus', title: 'Corydoras aeneus species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Corydoras-aeneus.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch07-fishbase-poecilia-reticulata': { id: 'batch07-fishbase-poecilia-reticulata', title: 'Poecilia reticulata species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Poecilia-reticulata.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch07-fishbase-hyphessobrycon-sweglesi': { id: 'batch07-fishbase-hyphessobrycon-sweglesi', title: 'Hyphessobrycon sweglesi species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hyphessobrycon-sweglesi.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch07-fishbase-hemigrammus-bleheri': { id: 'batch07-fishbase-hemigrammus-bleheri', title: 'Hemigrammus bleheri species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hemigrammus-bleheri.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch07-fishbase-hemigrammus-rodwayi': { id: 'batch07-fishbase-hemigrammus-rodwayi', title: 'Hemigrammus rodwayi species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hemigrammus-rodwayi.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch07-fishbase-prionobrama-filigera': { id: 'batch07-fishbase-prionobrama-filigera', title: 'Prionobrama filigera species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Prionobrama-filigera.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch07-fishbase-hyphessobrycon-herbertaxelrodi': { id: 'batch07-fishbase-hyphessobrycon-herbertaxelrodi', title: 'Hyphessobrycon herbertaxelrodi species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Hyphessobrycon-herbertaxelrodi.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch07-fishbase-paracheirodon-innesi': { id: 'batch07-fishbase-paracheirodon-innesi', title: 'Paracheirodon innesi species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Paracheirodon-innesi.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch07-fishbase-corydoras-panda': { id: 'batch07-fishbase-corydoras-panda', title: 'Corydoras panda species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Corydoras-panda.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch07-fishbase-corydoras-aeneus': { id: 'batch07-fishbase-corydoras-aeneus', title: 'Corydoras aeneus species summary', publisher: 'FishBase', url: 'https://www.fishbase.se/summary/Corydoras-aeneus.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed' },
  'batch07-itis-caridina-cantonensis': { id: 'batch07-itis-caridina-cantonensis', title: 'Caridina cantonensis ITIS taxonomic record', publisher: 'ITIS', url: 'https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=1173917', sourceType: 'government', reviewStatus: 'reviewed' },
  'batch04-raffles-geosesarma-dennerle': {
    id: 'batch04-raffles-geosesarma-dennerle', title: 'Geosesarma dennerle species description', publisher: 'Raffles Bulletin of Zoology',
    url: 'https://lkcnhm.nus.edu.sg/wp-content/uploads/sites/11/app/uploads/2017/06/63rbz003-013.pdf', sourceType: 'peer_reviewed', reviewStatus: 'reviewed',
  },
  'batch04-keys-anentome-helena': {
    id: 'batch04-keys-anentome-helena', title: "Anentome 'helena' freshwater mollusc account", publisher: 'Australian Government / Australian Museum freshwater mollusc keys',
    url: 'https://keys.lucidcentral.org/keys/v3/freshwater_molluscs/key/australian_freshwater_molluscs/Media/Html/entities/anentome_helena.htm', sourceType: 'government', reviewStatus: 'reviewed',
  },
  'batch04-itis-caridina-dennerli': {
    id: 'batch04-itis-caridina-dennerli', title: 'Caridina dennerli ITIS taxon record', publisher: 'Integrated Taxonomic Information System',
    url: 'https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=1173942', sourceType: 'government', reviewStatus: 'reviewed',
  },
  'batch04-worms-vittina-turrita': {
    id: 'batch04-worms-vittina-turrita', title: 'Vittina turrita WoRMS taxon record', publisher: 'World Register of Marine Species',
    url: 'https://www.marinespecies.org/aphia.php?p=taxlist&tName=Neritina+turrita', sourceType: 'professional_association', reviewStatus: 'reviewed',
  },
  'batch04-fishbase-amatitlania-nigrofasciata': {
    id: 'batch04-fishbase-amatitlania-nigrofasciata', title: 'Amatitlania nigrofasciata FishBase species summary', publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Amatitlania-nigrofasciata.html', sourceType: 'curated_husbandry', reviewStatus: 'reviewed',
  },
  'seriouslyfish-petitella-rhodostoma': {
    id: 'seriouslyfish-petitella-rhodostoma',
    title: 'Hemigrammus rhodostomus / Petitella rhodostoma (Rummy-nose tetra)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/hemigrammus-rhodostomus',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-petitella-rhodostoma': {
    id: 'fishbase-petitella-rhodostoma',
    title: 'Petitella rhodostoma species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Hemigrammus-rhodostomus.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-otocinclus-vittatus': {
    id: 'fishbase-otocinclus-vittatus',
    title: 'Otocinclus vittatus species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Otocinclus-vittatus.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'aquariumcoop-otocinclus-catfish': {
    id: 'aquariumcoop-otocinclus-catfish',
    title: 'Care Guide for Otocinclus Catfish',
    publisher: 'Aquarium Co-Op',
    url: 'https://www.aquariumcoop.com/blogs/aquarium/otocinclus-catfish',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'scotcat-otocinclus-vittatus': {
    id: 'scotcat-otocinclus-vittatus',
    title: 'Otocinclus vittatus Regan, 1904',
    publisher: 'ScotCat',
    url: 'https://www.scotcat.com/loricariidae/otocinclus_vittatus.htm',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-symphysodon-aequifasciatus': {
    id: 'seriouslyfish-symphysodon-aequifasciatus',
    title: 'Symphysodon aequifasciatus (Discus)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/symphysodon-aequifasciatus',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-symphysodon-aequifasciatus': {
    id: 'fishbase-symphysodon-aequifasciatus',
    title: 'Symphysodon aequifasciatus species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/11185',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-mikrogeophagus-ramirezi': {
    id: 'seriouslyfish-mikrogeophagus-ramirezi',
    title: 'Mikrogeophagus ramirezi (Ram)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/mikrogeophagus-ramirezi',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-mikrogeophagus-ramirezi': {
    id: 'fishbase-mikrogeophagus-ramirezi',
    title: 'Mikrogeophagus ramirezi species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/12305',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-apistogramma-agassizii': {
    id: 'seriouslyfish-apistogramma-agassizii',
    title: "Apistogramma agassizii (Agassizi's Dwarf Cichlid)",
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/apistogramma-agassizii/',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-apistogramma-agassizii': {
    id: 'fishbase-apistogramma-agassizii',
    title: "Apistogramma agassizii (Agassiz's dwarf cichlid) species summary",
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/Fieldguide/FieldGuideSummary.php?c_code=076&genusname=Apistogramma&speciesname=agassizii',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-trichopodus-leerii': {
    id: 'seriouslyfish-trichopodus-leerii',
    title: 'Trichopodus leerii (Pearl Gourami)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/trichopodus-leerii',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-trichopodus-leerii': {
    id: 'fishbase-trichopodus-leerii',
    title: 'Trichopodus leerii (Pearl gourami) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Trichopodus-leerii.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-phenacogrammus-interruptus': {
    id: 'seriouslyfish-phenacogrammus-interruptus',
    title: 'Phenacogrammus interruptus (Congo Tetra)',
    publisher: 'Seriously Fish',
    url: 'https://seriouslyfish.com/species/phenacogrammus-interruptus',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-phenacogrammus-interruptus': {
    id: 'fishbase-phenacogrammus-interruptus',
    title: 'Phenacogrammus interruptus (Congo tetra) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Phenacogrammus-interruptus.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-sahyadria-denisonii': {
    id: 'seriouslyfish-sahyadria-denisonii',
    title: 'Sahyadria denisonii (Red-line Torpedo Barb)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/sahyadria-denisonii',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-sahyadria-denisonii': {
    id: 'fishbase-sahyadria-denisonii',
    title: 'Dawkinsia denisonii (Denison barb) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Sahyadria-denisonii.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-hyphessobrycon-amandae': {
    id: 'seriouslyfish-hyphessobrycon-amandae',
    title: 'Hyphessobrycon amandae (Ember Tetra)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/hyphessobrycon-amandae',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-hyphessobrycon-amandae': {
    id: 'fishbase-hyphessobrycon-amandae',
    title: 'Hyphessobrycon amandae (Ember tetra) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Hyphessobrycon-amandae.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'aquariumhq-neocaridina-davidi': {
    id: 'aquariumhq-neocaridina-davidi',
    title: 'Cherry shrimp (Neocaridina davidi) care and compatibility',
    publisher: 'AquariumHQ',
    url: 'https://aquariumhq.app/invertebrates/cherry-shrimp',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'zootaxa-neocaridina-sexual-dimorphism': {
    id: 'zootaxa-neocaridina-sexual-dimorphism',
    title: 'Sexual dimorphism in a freshwater atyid shrimp with direct development',
    publisher: 'Zootaxa',
    url: 'https://pubmed.ncbi.nlm.nih.gov/27988685/',
    sourceType: 'peer_reviewed',
    reviewStatus: 'reviewed',
  },
  'aquaculture-research-neocaridina-life-cycle': {
    id: 'aquaculture-research-neocaridina-life-cycle',
    title: 'Breeding and life cycle of the ornamental freshwater shrimp Neocaridina davidi in a biofilm-based culture system',
    publisher: 'Aquaculture Research',
    url: 'https://doi.org/10.1111/are.14733',
    sourceType: 'peer_reviewed',
    reviewStatus: 'reviewed',
  },
  'aquendium-caridina-cantonensis': {
    id: 'aquendium-caridina-cantonensis',
    title: 'Crystal Red Shrimp (Caridina cantonensis) care guide',
    publisher: 'Aquendium',
    url: 'https://aquendium.com/species/crystal-red-shrimp/',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'aquariumhq-neritina-natalensis': {
    id: 'aquariumhq-neritina-natalensis',
    title: 'Nerite snail (Neritina natalensis) care and compatibility',
    publisher: 'AquariumHQ',
    url: 'https://aquariumhq.app/invertebrates/nerite-snail',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-gymnocorymbus-ternetzi': {
    id: 'seriouslyfish-gymnocorymbus-ternetzi',
    title: 'Gymnocorymbus ternetzi (Black Widow Tetra)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/gymnocorymbus-ternetzi',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-gymnocorymbus-ternetzi': {
    id: 'fishbase-gymnocorymbus-ternetzi',
    title: 'Gymnocorymbus ternetzi (Black tetra) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Gymnocorymbus-ternetzi',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-puntius-titteya': {
    id: 'seriouslyfish-puntius-titteya',
    title: 'Puntius titteya (Cherry Barb)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/puntius-titteya',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-puntius-titteya': {
    id: 'fishbase-puntius-titteya',
    title: 'Puntius titteya (Cherry barb) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Puntius_titteya.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-trigonostigma-heteromorpha': {
    id: 'seriouslyfish-trigonostigma-heteromorpha',
    title: 'Trigonostigma heteromorpha (Harlequin)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/trigonostigma-heteromorpha',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-trigonostigma-heteromorpha': {
    id: 'fishbase-trigonostigma-heteromorpha',
    title: 'Trigonostigma heteromorpha (Harlequin rasbora) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Trigonostigma_heteromorpha.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-xiphophorus-maculatus': {
    id: 'seriouslyfish-xiphophorus-maculatus',
    title: 'Xiphophorus maculatus (Platy)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/xiphophorus-maculatus',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-xiphophorus-maculatus': {
    id: 'fishbase-xiphophorus-maculatus',
    title: 'Xiphophorus maculatus (Southern platyfish) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Xiphophorus_maculatus.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-poecilia-sphenops': {
    id: 'seriouslyfish-poecilia-sphenops',
    title: 'Poecilia sphenops (Short-finned Molly/Black Molly)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/poecilia-sphenops',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-xiphophorus-hellerii': {
    id: 'seriouslyfish-xiphophorus-hellerii',
    title: 'Xiphophorus hellerii (Green Swordtail)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/xiphophorus-hellerii',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-xiphophorus-hellerii': {
    id: 'fishbase-xiphophorus-hellerii',
    title: 'Xiphophorus hellerii (Green swordtail) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.org/Summary/Xiphophorus-hellerii',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-poecilia-reticulata': {
    id: 'seriouslyfish-poecilia-reticulata',
    title: 'Poecilia reticulata (Guppy)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/poecilia-reticulata/',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-poecilia-reticulata': {
    id: 'fishbase-poecilia-reticulata',
    title: 'Poecilia reticulata (Guppy) species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/Poecilia-reticulata.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-paracheirodon-innesi': {
    id: 'seriouslyfish-paracheirodon-innesi',
    title: 'Paracheirodon innesi (Neon Tetra)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/paracheirodon-innesi',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-paracheirodon-axelrodi': {
    id: 'seriouslyfish-paracheirodon-axelrodi',
    title: 'Paracheirodon axelrodi (Cardinal Tetra)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/paracheirodon-axelrodi',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-tanichthys-albonubes': {
    id: 'seriouslyfish-tanichthys-albonubes',
    title: 'Tanichthys albonubes (White Cloud Mountain Minnow)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/tanichthys-albonubes',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-danio-rerio': {
    id: 'seriouslyfish-danio-rerio',
    title: "Brachydanio rerio (Zebra 'Danio')",
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/danio-rerio',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-glossolepis-incisus': {
    id: 'seriouslyfish-glossolepis-incisus',
    title: 'Glossolepis incisus (Red Rainbowfish)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/glossolepis-incisus',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-glossolepis-incisa': {
    id: 'fishbase-glossolepis-incisa',
    title: 'Glossolepis incisa species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/10477',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-chromobotia-macracanthus': {
    id: 'seriouslyfish-chromobotia-macracanthus',
    title: 'Chromobotia macracanthus (Clown Loach)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/chromobotia-macracanthus',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-chromobotia-macracanthus': {
    id: 'fishbase-chromobotia-macracanthus',
    title: 'Chromobotia macracanthus species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/10897',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-sewellia-lineolata': {
    id: 'seriouslyfish-sewellia-lineolata',
    title: 'Sewellia lineolata (Tiger Hillstream Loach)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/sewellia-lineolata',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-corydoras-pygmaeus': {
    id: 'seriouslyfish-corydoras-pygmaeus',
    title: 'Corydoras pygmaeus (Pygmy Cory)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/corydoras-pygmaeus',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'fishbase-corydoras-pygmaeus': {
    id: 'fishbase-corydoras-pygmaeus',
    title: 'Gastrodermus pygmaeus species summary',
    publisher: 'FishBase',
    url: 'https://www.fishbase.se/summary/corydoras-pygmaeus.html',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-corydoras-aeneus': {
    id: 'seriouslyfish-corydoras-aeneus',
    title: 'Corydoras aeneus (Bronze Cory)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/corydoras-aeneus',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-corydoras-panda': {
    id: 'seriouslyfish-corydoras-panda',
    title: 'Corydoras panda (Panda Cory)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/corydoras-panda',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-puntigrus-tetrazona': {
    id: 'seriouslyfish-puntigrus-tetrazona',
    title: 'Puntigrus tetrazona (Tiger Barb)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/puntigrus-tetrazona',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'convict-cichlid-territory-study': {
    id: 'convict-cichlid-territory-study',
    title: 'Sex Differences in How Territory Quality Affects Aggression in Convict Cichlids',
    publisher: 'Integrative and Comparative Biology',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8522484/',
    sourceType: 'peer_reviewed',
    reviewStatus: 'reviewed',
  },
  'small-snakehead-fws-assessment': {
    id: 'small-snakehead-fws-assessment',
    title: 'Ecological Risk Screening Summary: Small Snakehead (Channa asiatica)',
    publisher: 'U.S. Fish and Wildlife Service',
    url: 'https://www.fws.gov/sites/default/files/documents/Ecological-Risk-Screening-Summary-Small-Snakehead.pdf',
    sourceType: 'government',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-betta-splendens': {
    id: 'seriouslyfish-betta-splendens',
    title: 'Betta splendens (Siamese Fighting Fish)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/betta-splendens',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'seriouslyfish-pterophyllum-scalare': {
    id: 'seriouslyfish-pterophyllum-scalare',
    title: 'Pterophyllum scalare (Angelfish)',
    publisher: 'Seriously Fish',
    url: 'https://www.seriouslyfish.com/species/pterophyllum-scalare',
    sourceType: 'curated_husbandry',
    reviewStatus: 'reviewed',
  },
  'tamu-pterophyllum-scalare-reproduction': {
    id: 'tamu-pterophyllum-scalare-reproduction',
    title: 'Reproduction of Angelfish (Pterophyllum scalare)',
    publisher: 'Texas A&M AgriLife Extension',
    url: 'https://extension.rwfm.tamu.edu/wp-content/uploads/sites/8/2013/09/Reproduction-of-Angelfish-Pterphyllum-scalare.pdf',
    sourceType: 'government',
    reviewStatus: 'reviewed',
  },
};
export const getKnowledgeSource = (sourceId: string) => knowledgeSources[sourceId];

export const resolveKnowledgeSources = (sourceIds: string[]) => sourceIds
  .map(sourceId => knowledgeSources[sourceId])
  .filter((source): source is EvidenceSourceDto => Boolean(source));
