import type { SpeciesKnowledgeProfile } from './knowledge.types';
export type Phase2Batch06FieldAuthority = { status: 'reviewed_unknown'; citationIds: string[]; factEvidence: string };
type S = { id: string; source: string; title: string };
export const phase2Batch06Subjects: Record<string, S> = Object.fromEntries([
  ['sp_0005','batch08-fishbase-clithon-corona','Clithon corona taxon source'],['sp_0051','batch08-fishbase-acrossocheilus-fasciatus','Acrossocheilus fasciatus FishBase species summary'],['sp_0018','batch08-fishbase-chindongo-socolofi','Chindongo socolofi FishBase species summary'],['sp_0019','batch08-fishbase-pterophyllum-altum','Pterophyllum altum FishBase species summary'],['sp_0023','batch08-fishbase-zebrasoma-flavescens','Zebrasoma flavescens FishBase species summary'],['sp_0024','batch08-fishbase-paracanthurus-hepatus','Paracanthurus hepatus FishBase species summary'],['sp_0026','batch08-fishbase-hypostomus-plecostomus','Hypostomus plecostomus FishBase species summary'],['sp_0033','batch08-fishbase-clithon-corona','Clithon corona taxon source'],['sp_0034','batch08-worms-tylomelania','Tylomelania WoRMS taxonomic source'],['sp_0042','batch08-fishbase-pseudorasbora-parva','Pseudorasbora parva FishBase species summary'],
].map(([id,source,title]) => [id,{id,source,title}]));
const at='2026-09-16';
const ev=(s:S,f:string)=>({confidence:'unknown' as const,reviewStatus:'reviewed' as const,sourceIds:[s.source],reviewedAt:at,note:`${s.title} was reviewed for ${f}; the source does not establish a complete object-specific aquarium authority. No template, name inference, or base-species inheritance is promoted.`});
const make=(s:S):SpeciesKnowledgeProfile['knowledge']=>({sexIdentification:{title:'本轮不提供稳定的公母辨别规则',summary:'来源不足以形成稳定的对象级性别判断。',points:['不凭名称、品系或类别模板猜测性别。'],confidence:'unknown',source:{type:'unknown',label:'本批次性别证据不足',confidence:'unknown'},reliableFromLifeStage:'unknown',evidence:ev(s,'sex identification')},environment:{waterType:'unknown',evidence:ev(s,'environment')},socialBehavior:{mode:'unknown',summary:'来源不足以确认稳定水族箱社会模式。',evidence:ev(s,'social behavior')},spaceAndGrowth:{activityLevel:'unknown',evidence:ev(s,'space and growth')}});
export const phase2Batch06Knowledge=Object.fromEntries(Object.entries(phase2Batch06Subjects).map(([id,s])=>[id,make(s)])) as Record<string,SpeciesKnowledgeProfile['knowledge']>;
export const phase2Batch06Authority=Object.fromEntries(Object.entries(phase2Batch06Subjects).map(([id,s])=>[id,{feeding:{status:'reviewed_unknown',citationIds:[s.source],factEvidence:`${s.title} does not establish object-specific feeding authority.`},care:{status:'reviewed_unknown',citationIds:[s.source],factEvidence:`${s.title} does not establish object-specific care authority.`} as Phase2Batch06FieldAuthority}])) as Record<string,Partial<Record<'feeding'|'care',Phase2Batch06FieldAuthority>>>;
