import type { SpeciesKnowledgeProfile } from './knowledge.types';
import { phase2Batch30Knowledge } from './phase2Batch30Authority';

const reviewedAt = '2026-09-28';
const ev = (sourceIds: string[]) => ({
  confidence: 'verified' as const,
  reviewStatus: 'reviewed' as const,
  sourceIds,
  reviewedAt,
});

/** Exact-object runtime promotions for Compatibility priority batch 6. */
export const priorityCompatibilityKnowledgeBatch6_20260928: Record<string, SpeciesKnowledgeProfile['knowledge']> = {
  sp_0128: {
    ...phase2Batch30Knowledge.sp_0128,
    environment: {
      waterType: 'freshwater',
      temperatureRangeC: { min: 16, max: 24 },
      phRange: { min: 6.5, max: 8 },
      hardnessDgh: { min: 2, max: 15 },
      notes: ['需要洁净、高溶氧且有明显水流的成熟系统；不应把它作为普通温水社区鱼处理。'],
      evidence: ev(['seriouslyfish-beaufortia-kweichowensis', 'batch32-fishbase-beaufortia-kweichowensis']),
    },
    socialBehavior: {
      mode: 'group',
      minimumGroupSize: 6,
      recommendedGroupSize: { min: 6 },
      territoriality: 'low',
      finNipping: 'none',
      predationRisk: 'low',
      swimmingZone: 'bottom',
      swimmingPace: 'moderate',
      summary: '总体和平，但环境要求比性格更限制混养；自然中为松散聚集，至少 6 只更能表现正常行为，同类雄鱼会有轻度领地争执。',
      evidence: ev(['seriouslyfish-beaufortia-kweichowensis']),
    },
    spaceAndGrowth: {
      adultLengthCm: { max: 7.5, measurement: 'SL' },
      minVolumeLiters: 54,
      minTankLengthCm: 60,
      activityLevel: 'medium',
      swimmingZone: 'bottom',
      needsCover: true,
      spaceNotes: ['至少按 60 × 30 cm 底面积、约 54 L 规划；重点是成熟生物膜、高溶氧和持续水流。'],
      evidence: ev(['seriouslyfish-beaufortia-kweichowensis']),
    },
  },
  sp_0134: {
    ...phase2Batch30Knowledge.sp_0134,
    environment: {
      waterType: 'freshwater',
      temperatureRangeC: { min: 22, max: 30 },
      phRange: { min: 5, max: 8 },
      hardnessDgh: { min: 1, max: 12 },
      notes: ['适合成熟、种植丰富且水流较缓的系统。'],
      evidence: ev(['seriouslyfish-iriatherina-werneri', 'batch32-fishbase-iriatherina-werneri']),
    },
    socialBehavior: {
      mode: 'shoal',
      minimumGroupSize: 6,
      recommendedGroupSize: { min: 10 },
      territoriality: 'low',
      finNipping: 'none',
      finNipVulnerability: 'high',
      predationRisk: 'low',
      swimmingZone: 'middle',
      swimmingPace: 'slow',
      summary: '非常和平但并非普通社区缸“万能搭配”：至少 6 只、理想 10+；成熟雄鱼长鳍容易被咬鳍鱼针对，也容易被大型或过于活跃的同伴抢食。',
      evidence: ev(['seriouslyfish-iriatherina-werneri']),
    },
    spaceAndGrowth: {
      adultLengthCm: { max: 4, measurement: 'SL' },
      minVolumeLiters: 54,
      minTankLengthCm: 60,
      activityLevel: 'medium',
      swimmingZone: 'middle',
      needsCover: true,
      spaceNotes: ['至少按 60 × 30 cm 底面积、约 54 L 规划，并提供浓密水草与浮水植物。'],
      evidence: ev(['seriouslyfish-iriatherina-werneri']),
    },
  },
  sp_0135: {
    ...phase2Batch30Knowledge.sp_0135,
    environment: {
      waterType: 'freshwater',
      temperatureRangeC: { min: 24, max: 28 },
      phRange: { min: 7, max: 8 },
      hardnessDgh: { min: 15, max: 30 },
      notes: ['偏硬水；需要成熟、稳定且有良好溶氧的系统。'],
      evidence: ev(['seriouslyfish-pseudomugil-furcatus', 'batch32-fishbase-pseudomugil-furcatus']),
    },
    socialBehavior: {
      mode: 'shoal',
      minimumGroupSize: 8,
      recommendedGroupSize: { min: 10 },
      territoriality: 'none',
      finNipping: 'none',
      predationRisk: 'low',
      swimmingZone: 'middle',
      swimmingPace: 'fast',
      summary: '和平的群游鱼，至少 8–10 只；公鱼间展示通常不造成伤害。适合与体型、性情和水质需求相近的温和鱼搭配。',
      evidence: ev(['seriouslyfish-pseudomugil-furcatus']),
    },
    spaceAndGrowth: {
      adultLengthCm: { max: 6, measurement: 'SL' },
      minVolumeLiters: 54,
      minTankLengthCm: 60,
      activityLevel: 'medium',
      swimmingZone: 'middle',
      needsCover: true,
      spaceNotes: ['至少按 60 × 30 cm 底面积、约 54 L 规划。'],
      evidence: ev(['seriouslyfish-pseudomugil-furcatus']),
    },
  },
  sp_0136: {
    ...phase2Batch30Knowledge.sp_0136,
    environment: {
      waterType: 'freshwater',
      temperatureRangeC: { min: 26, max: 31 },
      phRange: { min: 4, max: 6.5 },
      hardnessDgh: { min: 0, max: 3 },
      notes: ['野生型需要极软酸性黑水；人工繁殖个体可稍宽容，但不能据此把其泛化成普通中性水社区鱼。'],
      evidence: ev(['seriouslyfish-sphaerichthys-osphromenoides', 'batch32-fishbase-sphaerichthys-osphromenoides']),
    },
    socialBehavior: {
      mode: 'group',
      minimumGroupSize: 6,
      recommendedGroupSize: { min: 6 },
      territoriality: 'low',
      finNipping: 'none',
      predationRisk: 'low',
      swimmingZone: 'middle',
      swimmingPace: 'slow',
      summary: '慢游、易受压且容易被大型或喧闹同伴抢食；虽然不是典型群游鱼，但来源明确建议不少于 6 只以维持正常同类互动。',
      evidence: ev(['seriouslyfish-sphaerichthys-osphromenoides']),
    },
    spaceAndGrowth: {
      adultLengthCm: { max: 5, measurement: 'SL' },
      minVolumeLiters: 54,
      minTankLengthCm: 60,
      activityLevel: 'low',
      swimmingZone: 'middle',
      needsCover: true,
      needsHidingPlaces: true,
      spaceNotes: ['约 60 × 30 cm、54 L 可用于群体起步；应保持昏暗、遮蔽和缓流。'],
      evidence: ev(['seriouslyfish-sphaerichthys-osphromenoides']),
    },
  },
};
