from pathlib import Path


def replace_once(path: str, old: str, new: str, label: str) -> None:
    file = Path(path)
    text = file.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 exact match, got {count}')
    file.write_text(text.replace(old, new, 1))


home = 'src/pages/Home.tsx'

replace_once(
    home,
    "import { getSpeciesFavoriteIds, subscribeToFavorites, toggleSpeciesFavorite } from '../services/favorites/favorites.service';\n",
    "import { getSpeciesFavoriteIds, setSpeciesFavoriteIds } from '../services/favorites/favorites.service';\nimport { getCollectionSnapshot, hydrateCollectionData, subscribeToCollection } from '../services/collection/collection.service';\nimport { getAquaGuideRepository, getCurrentAquaGuideRepository, resolveRepositoryMode } from '../services/repository/repository-provider';\nimport { loadAppStateFromStorage, patchLocalAppState } from '../services/storage/local-app-state';\nimport { selectAquariumSnapshot } from '../services/aquarium/aquarium-selection.service';\n",
    'Home repository imports',
)

old_effect = '''  useEffect(() => {\n    // Load aquariums\n    const saved = localStorage.getItem('aquariums');\n    if (saved) {\n      try {\n        const parsed: Aquarium[] = JSON.parse(saved);\n        if (parsed.length > 0) {\n          setDefaultAquarium(parsed[0]);\n          \n          // Collect owned fishes\n          const allAqFishes = parsed.flatMap(a => a.fishes);\n          const uniqueFishIds = Array.from(new Set(allAqFishes.map(af => af.fishId)));\n          const fishes = uniqueFishIds.map(id => fishData.find(f => f.id === id)).filter(Boolean) as Fish[];\n          setOwnedFishes(fishes);\n        }\n      } catch (e) {\n        console.error('Failed to parse aquariums', e);\n        setStorageError('本地鱼缸数据读取失败，请返回“我的鱼缸”检查数据。');\n      }\n    }\n\n    // Load deceased records\n    const savedDeceased = localStorage.getItem('deceasedRecords');\n    if (savedDeceased) {\n      try {\n        setDeceasedRecords(JSON.parse(savedDeceased));\n      } catch (error) {\n        console.error('Failed to parse deceased records', error);\n        setStorageError('部分历史记录读取失败，其他功能仍可继续使用。');\n      }\n    }\n\n    const refreshWishlist = () => setWishlistFishIds(new Set(getSpeciesFavoriteIds()));\n    refreshWishlist();\n    return subscribeToFavorites(refreshWishlist);\n  }, []);\n\n  const toggleWishlist = (id: string) => {\n    const isFavorite = toggleSpeciesFavorite(id);\n    setWishlistFishIds(new Set(getSpeciesFavoriteIds()));\n    \n    // If the currently selected fish was just un-wishlisted, close the dialog\n    if (selectedFish && selectedFish.id === id && !isFavorite) {\n      setSelectedFish(null);\n    }\n  };\n\n  const emptyAquariumFallback: Aquarium = {\n    id: 'empty_fallback',\n    name: '默认鱼缸',\n    fishes: [],\n    dimensions: { length: '60', width: '40', height: '40' },\n    waterType: 'Freshwater',\n    substrate: '无',\n    plants: [],\n    hardscape: [],\n    equipment: { filter: '瀑布过滤', heater: true, oxygen: false, light: '普通灯' }\n  };\n'''

new_effect = '''  const applyHomeSnapshot = () => {\n    const snapshot = getCollectionSnapshot();\n    const selectedAquarium = selectAquariumSnapshot(snapshot.appState.aquariums, [snapshot.appState.currentAquariumId]);\n    setDefaultAquarium(selectedAquarium || null);\n    const allAquariumFishes = snapshot.appState.aquariums.flatMap(aquarium => aquarium.fishes);\n    const uniqueFishIds = Array.from(new Set(allAquariumFishes.map(record => record.fishId)));\n    setOwnedFishes(uniqueFishIds.map(id => fishData.find(fish => fish.id === id)).filter(Boolean) as Fish[]);\n    setDeceasedRecords(snapshot.memorials);\n    setWishlistFishIds(new Set(snapshot.wishlistIds));\n  };\n\n  useEffect(() => {\n    let active = true;\n    const refresh = () => {\n      if (active) applyHomeSnapshot();\n    };\n    refresh();\n    const unsubscribe = subscribeToCollection(refresh);\n\n    void (async () => {\n      try {\n        const mode = await resolveRepositoryMode();\n        if (mode === 'cloud') {\n          const repository = getAquaGuideRepository(mode);\n          const aquariums = await repository.getAquariums();\n          const localState = loadAppStateFromStorage();\n          const selectedAquarium = selectAquariumSnapshot(aquariums, [localState.currentAquariumId]);\n          patchLocalAppState({\n            aquariums,\n            currentAquariumId: selectedAquarium?.id || '',\n          });\n        }\n        await hydrateCollectionData();\n        if (!active) return;\n        setStorageError('');\n        applyHomeSnapshot();\n      } catch (error) {\n        if (!active) return;\n        console.error('Failed to hydrate Home repository data', error);\n        applyHomeSnapshot();\n        setStorageError(isEn\n          ? 'Cloud sync is temporarily unavailable. Showing this device cache.'\n          : '云端同步暂时不可用，当前展示此设备缓存。');\n      }\n    })();\n\n    return () => {\n      active = false;\n      unsubscribe();\n    };\n  }, [isEn]);\n\n  const toggleWishlist = async (id: string) => {\n    const favorite = !getSpeciesFavoriteIds().includes(id);\n    try {\n      const repository = await getCurrentAquaGuideRepository();\n      await repository.updateFavorite({ type: 'species', catalogKey: id, favorite });\n      const favorites = await repository.getFavorites();\n      setSpeciesFavoriteIds(favorites.speciesCatalogKeys);\n      setWishlistFishIds(new Set(favorites.speciesCatalogKeys));\n      setStorageError('');\n      if (selectedFish && selectedFish.id === id && !favorite) setSelectedFish(null);\n    } catch (error) {\n      console.error('Failed to update Home wishlist', error);\n      setStorageError(isEn\n        ? 'Wishlist was not changed because it could not be saved.'\n        : '种草清单没有保存成功，本次修改未生效。');\n    }\n  };\n'''
replace_once(home, old_effect, new_effect, 'Home hydration/write boundary')

replace_once(
    home,
    '''        <div className="relative h-[250px] w-full bg-[#f8f9fa] overflow-hidden group">\n          <ThreeAquarium aquarium={defaultAquarium || emptyAquariumFallback} />\n          {/* Overlay to catch clicks and redirect, or leave interactive? */}\n          <Link to="/aquarium" className="absolute bottom-2 right-2 bg-white/80 backdrop-blur-sm text-ink px-2 py-1 rounded-sm text-[10px] font-bold shadow-sm opacity-0 group-hover:opacity-100 transition-opacity z-10 border border-white/50">\n            {isEn ? 'View Details' : '进入详细管理'}\n          </Link>\n        </div>\n''',
    '''        <div className="relative h-[250px] w-full bg-[#f8f9fa] overflow-hidden group">\n          {defaultAquarium ? (\n            <>\n              <ThreeAquarium aquarium={defaultAquarium} />\n              <Link to="/aquarium" className="absolute bottom-2 right-2 bg-white/80 backdrop-blur-sm text-ink px-2 py-1 rounded-sm text-[10px] font-bold shadow-sm opacity-0 group-hover:opacity-100 transition-opacity z-10 border border-white/50">\n                {isEn ? 'View Details' : '进入详细管理'}\n              </Link>\n            </>\n          ) : (\n            <div className="flex h-full flex-col items-center justify-center gap-3 px-6 text-center">\n              <Droplets className="h-8 w-8 text-ink/25" />\n              <div>\n                <p className="text-sm font-bold text-ink">{isEn ? 'No aquarium recorded yet' : '还没有记录鱼缸'}</p>\n                <p className="mt-1 text-xs font-medium text-ink/50">{isEn ? 'Create a tank to start tracking real care facts.' : '创建鱼缸后，这里会展示真实的养护状态。'}</p>\n              </div>\n              <Link to="/aquarium" className="rounded-full bg-emerald-700 px-4 py-2 text-xs font-bold text-white">\n                {isEn ? 'Create aquarium' : '去创建鱼缸'}\n              </Link>\n            </div>\n          )}\n        </div>\n''',
    'Home factual empty aquarium state',
)

replace_once(
    home,
    '                    onClick={() => toggleWishlist(selectedFish.id)}\n',
    '                    onClick={() => void toggleWishlist(selectedFish.id)}\n',
    'Home async wishlist click',
)
